name: Deploy to SSH host

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Pull Production
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT || 22 }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Open Dir            
            cd "${{ secrets.REMOTE_DIR }}"
            npm ci --omit=dev

            # Create .env file
            > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASS }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "SHADOW_USER=null" >> .env
            echo "SHADOW_PASSWORD=null" >> .env
            echo "SHADOW_HOST=null" >> .env
            echo "SHADOW_PORT=null" >> .env
            echo "SHADOW_NAME=null" >> .env

            # Generate Prisma
            npx prisma migrate deploy
            npx prisma generate

            # Pull Updates and Install Dependencies
            cd "${{ secrets.REMOTE_DIR }}"
            git pull origin production
            npm run build

            # Start or restart with pm2 (assumes pm2 is installed globally)
            if pm2 describe jrprogramming > /dev/null; then
             pm2 reload jrprogramming || pm2 restart jrprogramming
            else
              pm2 start npm --name "jrprogramming" -- start
            fi